/**
 * @swagger
 * tags:
 *   - name: Auth
 *     description: Login, register, and token refresh
 *
 * /api/login:
 *   post:
 *     tags: [Auth]
 *     summary: Login
 *     security: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [email, password]
 *             properties:
 *               username:    { type: string, example: JohnDoe@ra-personel.ac.th }
 *               password:    { type: string, example: secret123 }
 *     responses:
 *       200:
 *         description: JWT access + refresh tokens
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 accessToken:  { type: string }
 *                 refreshToken: { type: string }
 *       401:
 *         description: Invalid credentials
 *
 * /api/login/register:
 *   post:
 *     tags: [Auth]
 *     summary: Register new user
 *     security: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [username, password]
 *             properties:
 *               username:  { type: string, example: M6/2-group1 }
 *               password:  { type: string, example: secret123 }
 *               classroom: { type: string, example: M6/2 }
 *     responses:
 *       201:
 *         description: User created
 *       400:
 *         description: username/password missing or username format not recognized
 *
 * /api/refresh:
 *   post:
 *     tags: [Auth]
 *     summary: Refresh access token
 *     security: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [refreshToken]
 *             properties:
 *               refreshToken: { type: string }
 *     responses:
 *       200:
 *         description: New access token
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 accessToken: { type: string }
 *       401:
 *         description: Invalid or expired refresh token
 *
 * /api/distribute-budget:
 *   post:
 *     tags: [Auth]
 *     summary: Distribute budget to all classrooms (admin only)
 *     security: [{ bearerAuth: [] }]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [centralBudget]
 *             properties:
 *               centralBudget: { type: number, example: 50000 }
 *     responses:
 *       200:
 *         description: Budget distributed
 *       400:
 *         description: centralBudget missing or not a number
 *       403:
 *         description: Insufficient role (admin only)
 */
import { Router } from 'express';
import { fileURLToPath } from 'url';
import { readdirSync } from 'fs';
import { join, dirname } from 'path';
import { validate, requireRole } from '../middleware/auth.middleware.js';
import * as Login from '../controllers/user.controller.js';

const rootRouter = Router();
const __dirname = dirname(fileURLToPath(import.meta.url));

// Public routes (no auth)
rootRouter.post("/login", Login.userLogin);
rootRouter.post("/login/register", Login.userRegister);
rootRouter.post("/refresh", Login.userRefresh);

// Auth wall — everything below requires validated token (Access token generated by JWT access secret)
rootRouter.use(validate);

rootRouter.post("/distribute-budget", requireRole(2), Login.triggerDistribute);

// Auto-mount sub-routers
for (const file of readdirSync(__dirname)) {
  if (!file.endsWith(".routes.js") || file === "index.js") continue;
  try {
    const mod = await import(join(__dirname, file));
    const subRouter = mod.default ?? mod;
    rootRouter.use(subRouter);
    console.log(`[Route Loaded]: ${file}`);
  } catch (err) {
    console.error(`[Route Error]: Could not load "${file}": ${err.message}`);
  }
}

export default rootRouter;
